[package]
name = "uniq"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
md5 = "0.7"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true
