[package]
name = "uniq"
version = "0.4.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
md5 = "0.7"
rayon = "1.7.0"

[profile.release]
codegen-units = 1
lto = true
strip = true
